<?php function sehirnormal($a){
	if ($a == 1) { $a = "Adana"; echo $a; }
	elseif ($a == 2) { $a = "Adıyaman"; echo $a; }
	elseif ($a == 3) { $a = "Afyonkarahisar"; echo $a; }
	elseif ($a == 4) { $a = "Ağrı"; echo $a; }
	elseif ($a == 5) { $a = "Amasya"; echo $a; }
	elseif ($a == 6) { $a = "Ankara"; echo $a; }
	elseif ($a == 7) { $a = "Antalya"; echo $a; }
	elseif ($a == 8) { $a = "Artvin"; echo $a; }
	elseif ($a == 9) { $a = "Aydın"; echo $a; }
	elseif ($a == 10) { $a = "Balıkesir"; echo $a; }
	elseif ($a == 11) { $a = "Bilecik"; echo $a; }
	elseif ($a == 12) { $a = "Bingöl"; echo $a; }
	elseif ($a == 13) { $a = "Bitlis"; echo $a; }
	elseif ($a == 14) { $a = "Bolu"; echo $a; }
	elseif ($a == 15) { $a = "Burdur"; echo $a; }
	elseif ($a == 16) { $a = "Bursa"; echo $a; }
	elseif ($a == 17) { $a = "Çanakkale"; echo $a; }
	elseif ($a == 18) { $a = "Çankırı"; echo $a; }
	elseif ($a == 19) { $a = "Çorum"; echo $a; }
	elseif ($a == 20) { $a = "Denizli"; echo $a; }
	elseif ($a == 21) { $a = "Diyarbakır"; echo $a; }
	elseif ($a == 22) { $a = "Edirne"; echo $a; }
	elseif ($a == 23) { $a = "Elazığ"; echo $a; }
	elseif ($a == 24) { $a = "Erzincan"; echo $a; }
	elseif ($a == 25) { $a = "Erzurum"; echo $a; }
	elseif ($a == 26) { $a = "Eskişehir"; echo $a; }
	elseif ($a == 27) { $a = "Gaziantep"; echo $a; }
	elseif ($a == 28) { $a = "Giresun"; echo $a; }
	elseif ($a == 29) { $a = "Gümüşhane"; echo $a; }
	elseif ($a == 30) { $a = "Hakkâri"; echo $a; }
	elseif ($a == 31) { $a = "Hatay"; echo $a; }
	elseif ($a == 32) { $a = "Isparta"; echo $a; }
	elseif ($a == 33) { $a = "Mersin"; echo $a; }
	elseif ($a == 34) { $a = "İstanbul"; echo $a; }
	elseif ($a == 35) { $a = "İzmir"; echo $a; }
	elseif ($a == 36) { $a = "Kars"; echo $a; }
	elseif ($a == 37) { $a = "Kastamonu"; echo $a; }
	elseif ($a == 38) { $a = "Kayseri"; echo $a; }
	elseif ($a == 39) { $a = "Kırklareli"; echo $a; }
	elseif ($a == 40) { $a = "Kırşehir"; echo $a; }
	elseif ($a == 41) { $a = "Kocaeli"; echo $a; }
	elseif ($a == 42) { $a = "Konya"; echo $a; }
	elseif ($a == 43) { $a = "Kütahya"; echo $a; }
	elseif ($a == 44) { $a = "Malatya"; echo $a; }
	elseif ($a == 45) { $a = "Manisa"; echo $a; }
	elseif ($a == 46) { $a = "Kahramanmaraş"; echo $a; }
	elseif ($a == 47) { $a = "Mardin"; echo $a; }
	elseif ($a == 48) { $a = "Muğla"; echo $a; }
	elseif ($a == 49) { $a = "Muş"; echo $a; }
	elseif ($a == 50) { $a = "Nevşehir"; echo $a; }
	elseif ($a == 51) { $a = "Niğde"; echo $a; }
	elseif ($a == 52) { $a = "Ordu"; echo $a; }
	elseif ($a == 53) { $a = "Rize"; echo $a; }
	elseif ($a == 54) { $a = "Sakarya"; echo $a; }
	elseif ($a == 55) { $a = "Samsun"; echo $a; }
	elseif ($a == 56) { $a = "Siirt"; echo $a; }
	elseif ($a == 57) { $a = "Sinop"; echo $a; }
	elseif ($a == 58) { $a = "Sivas"; echo $a; }
	elseif ($a == 59) { $a = "Tekirdağ"; echo $a; }
	elseif ($a == 60) { $a = "Tokat"; echo $a; }
	elseif ($a == 61) { $a = "Trabzon"; echo $a; }
	elseif ($a == 62) { $a = "Tunceli"; echo $a; }
	elseif ($a == 63) { $a = "Şanlıurfa"; echo $a; }
	elseif ($a == 64) { $a = "Uşak"; echo $a; }
	elseif ($a == 65) { $a = "Van"; echo $a; }
	elseif ($a == 66) { $a = "Yozgat"; echo $a; }
	elseif ($a == 67) { $a = "Zonguldak"; echo $a; }
	elseif ($a == 68) { $a = "Aksaray"; echo $a; }
	elseif ($a == 69) { $a = "Bayburt"; echo $a; }
	elseif ($a == 70) { $a = "Karaman"; echo $a; }
	elseif ($a == 71) { $a = "Kırıkkale"; echo $a; }
	elseif ($a == 72) { $a = "Batman"; echo $a; }
	elseif ($a == 73) { $a = "Şırnak"; echo $a; }
	elseif ($a == 74) { $a = "Bartın"; echo $a; }
	elseif ($a == 75) { $a = "Ardahan"; echo $a; }
	elseif ($a == 76) { $a = "Iğdır"; echo $a; }
	elseif ($a == 77) { $a = "Yalova"; echo $a; }
	elseif ($a == 78) { $a = "Karabük"; echo $a; }
	elseif ($a == 79) { $a = "Kilis"; echo $a; }
	elseif ($a == 80) { $a = "Osmaniye"; echo $a; }
	elseif ($a == 81) { $a = "Düzce"; echo $a; }
}
