function sehir($a){
		if ($a == "adana") { $a = "Adana"; echo $a; }
		elseif ($a == "adiyaman") { $a = "Adıyaman"; echo $a; }
		elseif ($a == "afyonkarahisar") { $a = "Afyonkarahisar"; echo $a; }
		elseif ($a == "agri") { $a = "Ağrı"; echo $a; }
		elseif ($a == "amasya") { $a = "Amasya"; echo $a; }
		elseif ($a == "ankara") { $a = "Ankara"; echo $a; }
		elseif ($a == "antalya") { $a = "Antalya"; echo $a; }
		elseif ($a == "artvin") { $a = "Artvin"; echo $a; }
		elseif ($a == "aydin") { $a = "Aydın"; echo $a; }
		elseif ($a == "balikesir") { $a = "Balıkesir"; echo $a; }
		elseif ($a == "bilecik") { $a = "Bilecik"; echo $a; }
		elseif ($a == "bingol") { $a = "Bingöl"; echo $a; }
		elseif ($a == "bitlis") { $a = "Bitlis"; echo $a; }
		elseif ($a == "bolu") { $a = "Bolu"; echo $a; }
		elseif ($a == "burdur") { $a = "Burdur"; echo $a; }
		elseif ($a == "bursa") { $a = "Bursa"; echo $a; }
		elseif ($a == "canakkale") { $a = "Çanakkale"; echo $a; }
		elseif ($a == "cankiri") { $a = "Çankırı"; echo $a; }
		elseif ($a == "corum") { $a = "Çorum"; echo $a; }
		elseif ($a == "denizli") { $a = "Denizli"; echo $a; }
		elseif ($a == "diyarbakir") { $a = "Diyarbakır"; echo $a; }
		elseif ($a == "edirne") { $a = "Edirne"; echo $a; }
		elseif ($a == "elazıg") { $a = "Elazığ"; echo $a; }
		elseif ($a == "erzincan") { $a = "Erzincan"; echo $a; }
		elseif ($a == "erzurum") { $a = "Erzurum"; echo $a; }
		elseif ($a == "eskisehir") { $a = "Eskişehir"; echo $a; }
		elseif ($a == "gaziantep") { $a = "Gaziantep"; echo $a; }
		elseif ($a == "giresun") { $a = "Giresun"; echo $a; }
		elseif ($a == "gumushane") { $a = "Gümüşhane"; echo $a; }
		elseif ($a == "hakkari") { $a = "Hakkâri"; echo $a; }
		elseif ($a == "hatay") { $a = "Hatay"; echo $a; }
		elseif ($a == "isparta") { $a = "Isparta"; echo $a; }
		elseif ($a == "mersin") { $a = "Mersin"; echo $a; }
		elseif ($a == "istanbul") { $a = "İstanbul"; echo $a; }
		elseif ($a == "izmir") { $a = "İzmir"; echo $a; }
		elseif ($a == "kars") { $a = "Kars"; echo $a; }
		elseif ($a == "kastamonu") { $a = "Kastamonu"; echo $a; }
		elseif ($a == "kayseri") { $a = "Kayseri"; echo $a; }
		elseif ($a == "kirklareli") { $a = "Kırklareli"; echo $a; }
		elseif ($a == "kirsehir") { $a = "Kırşehir"; echo $a; }
		elseif ($a == "kocaeli") { $a = "Kocaeli"; echo $a; }
		elseif ($a == "konya") { $a = "Konya"; echo $a; }
		elseif ($a == "kutahya") { $a = "Kütahya"; echo $a; }
		elseif ($a == "malatya") { $a = "Malatya"; echo $a; }
		elseif ($a == "manisa") { $a = "Manisa"; echo $a; }
		elseif ($a == "kahramanmaras") { $a = "Kahramanmaraş"; echo $a; }
		elseif ($a == "mardin") { $a = "Mardin"; echo $a; }
		elseif ($a == "mugla") { $a = "Muğla"; echo $a; }
		elseif ($a == "mus") { $a = "Muş"; echo $a; }
		elseif ($a == "nevsehir") { $a = "Nevşehir"; echo $a; }
		elseif ($a == "nigde") { $a = "Niğde"; echo $a; }
		elseif ($a == "ordu") { $a = "Ordu"; echo $a; }
		elseif ($a == "rize") { $a = "Rize"; echo $a; }
		elseif ($a == "sakarya") { $a = "Sakarya"; echo $a; }
		elseif ($a == "samsun") { $a = "Samsun"; echo $a; }
		elseif ($a == "siirt") { $a = "Siirt"; echo $a; }
		elseif ($a == "sinop") { $a = "Sinop"; echo $a; }
		elseif ($a == "sivas") { $a = "Sivas"; echo $a; }
		elseif ($a == "tekirdag") { $a = "Tekirdağ"; echo $a; }
		elseif ($a == "tokat") { $a = "Tokat"; echo $a; }
		elseif ($a == "trabzon") { $a = "Trabzon"; echo $a; }
		elseif ($a == "tunceli") { $a = "Tunceli"; echo $a; }
		elseif ($a == "sanliurfa") { $a = "Şanlıurfa"; echo $a; }
		elseif ($a == "usak") { $a = "Uşak"; echo $a; }
		elseif ($a == "van") { $a = "Van"; echo $a; }
		elseif ($a == "yozgat") { $a = "Yozgat"; echo $a; }
		elseif ($a == "zonguldak") { $a = "Zonguldak"; echo $a; }
		elseif ($a == "aksaray") { $a = "Aksaray"; echo $a; }
		elseif ($a == "bayburt") { $a = "Bayburt"; echo $a; }
		elseif ($a == "karaman") { $a = "Karaman"; echo $a; }
		elseif ($a == "kirikkale") { $a = "Kırıkkale"; echo $a; }
		elseif ($a == "batman") { $a = "Batman"; echo $a; }
		elseif ($a == "sirnak") { $a = "Şırnak"; echo $a; }
		elseif ($a == "bartin") { $a = "Bartın"; echo $a; }
		elseif ($a == "ardahan") { $a = "Ardahan"; echo $a; }
		elseif ($a == "igdir") { $a = "Iğdır"; echo $a; }
		elseif ($a == "yalova") { $a = "Yalova"; echo $a; }
		elseif ($a == "karabuk") { $a = "Karabük"; echo $a; }
		elseif ($a == "kilis") { $a = "Kilis"; echo $a; }
		elseif ($a == "osmaniye") { $a = "Osmaniye"; echo $a; }
		elseif ($a == "duzce") { $a = "Düzce"; echo $a; }
	}
